site_name: 'soluble-japha'
site_author: 'Sébastien Vanvelthem'
site_url: http://docs.soluble.io/soluble-japha/
site_description: >-
  PHP java bridge client from JVM interoperability.

# Repository
repo_name: 'soluble-japha'
repo_url: 'https://github.com/belgattitude/soluble-japha'

# Copyright
copyright: 'Copyright &copy; 2017-2020 Sébastien Vanvelthem'

docs_dir: doc
site_dir: build/doc
edit_uri: https://github.com/belgattitude/soluble-japha/edit/master/doc/


nav:
  - { 'Introduction': index.md }
  - { 'Installation': [
  { 'PHP install': install_client.md },
  { 'JavaBridge server': install_server.md }
  ]
  }
  - { 'Connection':  bridge_connection.md }
  - { 'Usage': [

  { 'Language basics': language_basics.md },
  { 'Useful functions': language_useful_functions.md },
  { 'Handling exceptions': language_exceptions.md },

  ]}
  - { 'Recipes': language_recipes.md }
  - { 'Performance': [
  { 'How it works': bridge_how_it_works.md },
  { 'Optimizations': language_optimizations.md },
  { 'Benchmarks': bridge_benchmarks.md },
  ]
  }
  - { 'Advanced': [
  { 'Servlet functions': bridge_servlet_functions.md },
  { 'Servlet session': bridge_servlet_session.md },
  { 'Servlet context': bridge_servlet_context.md }
  ]}
  - { 'Notes': [
  { 'Limitations': notes_limitations.md },
  { 'Legacy version': notes_legacy.md },
  { 'Java install': server/install_java.md },
  { 'Tomcat install': server/install_tomcat.md },

  ]}
  - { 'Standards & quality': notes_implementation.md }


# Documentation and theme
theme:
  name: material

  # 404 page
  #static_templates:
  #  - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  #features:
    #- tabs
    #- instant
  palette:
    primary: deep-orange
    accent: light blue
  font:
    text: IBM Plex Sans
    code: SFMono-Regular,Consolas,Menlo,monospace

# Plugins
plugins:
  - search

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/belgattitude/soluble-japha

extra_javascript:
  - _assets/js/mermaid-8.5.0.min.js
extra_css:
  - _assets/css/mermaid.css
  - _assets/css/monokai.css
  - _assets/css/style.css

#google_analytics:
#  - 'UA-xxxxxxxx-x'
#  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
        # - pymdownx.highlight:
      #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


